name: RandomEncounters
author: ArchmageInc
main: com.archmageinc.RandomEncounters.RandomEncounters
version: 0.2
description: Generates configurable random encounters in newly generated chunks
depend: [WorldEdit]