name: RandomEncounters
author: ArchmageInc
main: com.archmageinc.RandomEncounters.RandomEncounters
version: 0.3
description: Generates configurable random encounters in newly generated chunks
depend: [WorldEdit]
commands:
    re:
        description: Random Encounters manipulation
        usage: /re [place, reload]